apiVersion: v2
name: uptime-kuma
description: A Helm chart for Uptime Kuma cluster deployment on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - uptime
  - monitoring
  - kuma
  - cluster
maintainers:
  - name: IBuyPower
home: https://github.com/louislam/uptime-kuma
sources:
  - https://github.com/markku636/uptime-kuma-cluster
